#Lists and Loops (1 hour)
- Lists: creating, indexing, slicing
- Looping through lists using a for-loop
- List comprehension
Defining and using custom functions with def
Working with sublists for data manipulation
Functions and Modules (1 hour)
- Defining functions: parameters, return values
- Scope of variables: global vs. local
- Introduction to Python modules and libraries
Introduction to and its operations
Converting a into a
Generating and exporting data using Python
Reading data from
Using for positional indexing
Understanding of selecting rows/columns
Grouping data with operations
Reading data from
Understanding how to properly locate Excel or CSV files
Introduction to NumPy and Pandas (1 hour)
- Basics of NumPy: arrays, operations
- Introduction to Pandas: Series, DataFrame
- Data manipulation with NumPy and Pandas

In [ ]:
hatil_furniture_store = ["Table", "Chair", "Bed"]
hatil_furniture_store

['Table', 'Chair', 'Bed']

In [ ]:
hatil_furniture_store[1]

'Chair'

In [ ]:
print(hatil_furniture_store)

['Table', 'Chair', 'Bed']


In [ ]:
print(hatil_furniture_store[1])

Chair


##Def function or method

In [ ]:
def addition(x):
    x = x+x
    return x

In [ ]:
addition(10)

20

In [ ]:
def Square(x):
    x = x**2
    return x

In [ ]:
results = Square(5)

In [ ]:
results

25

In [ ]:
def add(x,y):
    output = x + y
    return output

In [ ]:
add(5,3)

8

#Sub List

In [ ]:
furniture = ["Table", "Chair", "Bed", "Rack","lohar chair", "almari"]

furniture_sub_list = furniture[1:4]
furniture_sub_list

['Chair', 'Bed', 'Rack']

In [ ]:
furniture[0]

'Table'

In [ ]:
print(furniture_sub_list)

['Chair', 'Bed', 'Rack']


In [ ]:
for anyvalue in furniture_sub_list:
    print(anyvalue)

Chair
Bed
Rack


#Hidden Index find out with enumerate Function

In [ ]:
for SI, item in enumerate(furniture):
    print(f"Index {SI}: item {item}")

Index 0: item Table
Index 1: item Chair
Index 2: item Bed
Index 3: item Rack
Index 4: item lohar chair
Index 5: item almari


#ZIP Function

In [ ]:
ID = [1,2,3,4,5,6]
furniture = ["Table", "Chair", "Bed", "Rack", "Self", "Almirae"]
price = [1000, 100, 5000, 1200, 1400, 15000]


In [ ]:
for ID, furniture, price in zip(ID, furniture, price):
    print(f"The {ID} of {furniture} price is: {price}")

The 1 of Table price is: 1000
The 2 of Chair price is: 100
The 3 of Bed price is: 5000
The 4 of Rack price is: 1200
The 5 of Self price is: 1400
The 6 of Almirae price is: 15000


#List Item Remove

In [ ]:
furniture = ["Table", "Chair", "Bed", "Rack", "Self", "Almirae"]
furniture.remove("Bed")
furniture

['Table', 'Chair', 'Rack', 'Self', 'Almirae']

In [ ]:
furniture = ["Table", "Chair", "Bed", "Rack", "Self", "Almirae"]
del furniture[3]
furniture

['Table', 'Chair', 'Bed', 'Self', 'Almirae']

In [ ]:
for anyvalue in furniture:
    print(anyvalue)

Table
Chair
Rack
Self
Almirae


#List item Data Insertion

In [ ]:
furniture.insert(3,"bookself")
furniture

['Table', 'Chair', 'Bed', 'bookself', 'Self', 'Almirae']

#lenth Data

In [ ]:
len(furniture)

6

#Dictionary

In [ ]:
furniture_dictionary = {"Table" : 1000, "Chair":500, "Bed": 15000, "Rack": 1200, "Self": 1500, "Almirae": 30000}
furniture_dictionary

{'Table': 1000,
 'Chair': 500,
 'Bed': 15000,
 'Rack': 1200,
 'Self': 1500,
 'Almirae': 30000}

In [ ]:
furniture_dictionary.values()

dict_values([1000, 500, 15000, 1200, 1500, 30000])

In [ ]:
furniture_dictionary.keys()

dict_keys(['Table', 'Chair', 'Bed', 'Rack', 'Self', 'Almirae'])

# Numpy & Pands

In [2]:
# Pandas - Reading different file formats and create Dataframes using them
import pandas as py
# Numericals Python - ND Array mathematical operations
import numpy as np

In [ ]:
any = np.array(["Table", "Chair", "Bed", "Rack", "Self", "Almirae"])   # 1-D Array , Create a 1Rank numpy array
display(any)

array(['Table', 'Chair', 'Bed', 'Rack', 'Self', 'Almirae'], dtype='<U7')

In [ ]:
arr_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])   # 1-D Array , Create a 1Rank numpy array
display(arr_1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
print(arr_1)

[0 1 2 3 4 5 6 7 8]


In [ ]:
arr_1.ndim

1

In [ ]:
arr_1.shape

(9,)

In [ ]:
# Returns data types as N-Dimentional Array
type(arr_1)

numpy.ndarray

#Types of Numpy Array

In [ ]:
arr_2 = np.array([[10, 20, 30, 40, 50, 60, 70],[1, 2, 3, 4, 5, 6, 7]])       # Choose 2D Array , this is to create 2-Rank numpy array
arr_2

array([[10, 20, 30, 40, 50, 60, 70],
       [ 1,  2,  3,  4,  5,  6,  7]])

In [ ]:
print(arr_2)

[[10 20 30 40 50 60 70]
 [ 1  2  3  4  5  6  7]]


In [ ]:
# dimentionality
print(arr_2.ndim)
# array shape
print(arr_2.shape)

2
(2, 7)


In [ ]:
arr_3 = np.array([[[10, 20, 30, 40, 50, 60, 70],
                  [11, 12, 13, 14, 15, 16, 17]],

                  [[10, 20, 30, 40, 50, 60, 70],
                  [11, 12, 13, 14, 15, 16, 17]],

                  [[10, 20, 30, 40, 50, 60, 70],
                  [11, 12, 13, 14, 15, 16, 17]]])
display(arr_3)

array([[[10, 20, 30, 40, 50, 60, 70],
        [11, 12, 13, 14, 15, 16, 17]],

       [[10, 20, 30, 40, 50, 60, 70],
        [11, 12, 13, 14, 15, 16, 17]],

       [[10, 20, 30, 40, 50, 60, 70],
        [11, 12, 13, 14, 15, 16, 17]]])

In [ ]:
print(arr_3)

[[[10 20 30 40 50 60 70]
  [11 12 13 14 15 16 17]]

 [[10 20 30 40 50 60 70]
  [11 12 13 14 15 16 17]]

 [[10 20 30 40 50 60 70]
  [11 12 13 14 15 16 17]]]


In [ ]:
arr_3.ndim

3

In [ ]:
arr_3.shape

(3, 2, 7)

#Random 1D array geenerator

In [ ]:
# arange function will not include last value
arr_4 = np.arange(25, 52)
arr_4

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51])

In [ ]:
# arange function will not include last value
arr_4 = np.arange(25, 50)
arr_4

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
arr_5 = arr_4.reshape(5, 5)
arr_5

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [ ]:
arr_5.transpose()

array([[25, 30, 35, 40, 45],
       [26, 31, 36, 41, 46],
       [27, 32, 37, 42, 47],
       [28, 33, 38, 43, 48],
       [29, 34, 39, 44, 49]])

In [ ]:
arr_6 = arr_4.reshape(3,3,3)
arr_6

array([[[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33]],

       [[34, 35, 36],
        [37, 38, 39],
        [40, 41, 42]],

       [[43, 44, 45],
        [46, 47, 48],
        [49, 50, 51]]])

In [ ]:
# Image Kernals
np_ones_any = np.ones(shape = (5,5))
np_ones_any

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np_ones_3D = np.ones(shape = (5,5,5))

In [ ]:
np_ones_3D

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#Kernel

In [ ]:
# Kernal matrix is a matrix that shifts over input image data and performs dot product with input matrix and gets output matrix
kernel = np_ones_any * (1/49)
kernel

array([[0.02040816, 0.02040816, 0.02040816, 0.02040816, 0.02040816],
       [0.02040816, 0.02040816, 0.02040816, 0.02040816, 0.02040816],
       [0.02040816, 0.02040816, 0.02040816, 0.02040816, 0.02040816],
       [0.02040816, 0.02040816, 0.02040816, 0.02040816, 0.02040816],
       [0.02040816, 0.02040816, 0.02040816, 0.02040816, 0.02040816]])

#Create a Dataframe

In [ ]:
dataset = py.read_csv('https://raw.githubusercontent.com/kb22/Heart-Disease-Prediction/refs/heads/master/dataset.csv', sep = ',', header = 0)
dataset

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
HD = py.read_csv("/content/drive/MyDrive/Spring 2025 Course Deep Learning/2nd class/dataset.csv")

In [5]:
HD

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [6]:
HD.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [7]:
HD.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [8]:
HD.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0