In [13]:
print("Hello World")

Hello World


In [16]:
import numpy as np
import pandas as pd

In [17]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [21]:
type(np.array([1,2,3,4]))

numpy.ndarray

random generate array   

In [73]:
array_4 = np.arange(0,27)
array_4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [63]:
# array_5 = array_4.reshape(5,5)
# array_5

In [66]:
array_6 = array_4.reshape(3,3,3)
array_6

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [72]:
one =np.ones(shape=(3,3,3))
print(one)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [94]:
kernel = np.ones(shape=(3,3))
test = kernel * (1/49)
print(test)

[[0.02040816 0.02040816 0.02040816]
 [0.02040816 0.02040816 0.02040816]
 [0.02040816 0.02040816 0.02040816]]
